// Generate release metadata from one source and the configured Git remote.
const fs = require('node:fs'), path = require('node:path'), { execFileSync } = require('node:child_process');
const root = path.resolve(__dirname, '..');
const config = JSON.parse(fs.readFileSync(path.join(root, 'release.json'), 'utf8'));
if (config.officialVersion !== '7.1.1' || !/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(config.localVersion)) throw new Error('Invalid official/local version.');
const version = config.officialVersion + '-local.' + config.localVersion;
if (!config.updates.length || config.updates[0].version !== version || config.updates[0].date !== config.date) throw new Error('Latest update does not match the release.');
const remote = execFileSync('git', ['config', '--get', 'remote.' + config.repositoryRemote + '.url'], { cwd: root, encoding: 'utf8' }).trim();
let repository = remote.replace(/^git@github\.com:/, 'https://github.com/').replace(/^ssh:\/\/git@github\.com\//, 'https://github.com/').replace(/\.git$/, '');
const url = new URL(repository);
if (url.protocol !== 'https:' || url.hostname !== 'github.com' || url.username || url.password || !/^\/[^/]+\/[^/]+$/.test(url.pathname)) throw new Error('Expected a GitHub repository remote.');
config.updates.forEach(update => {
    if (!update.version || !/^\d{4}-\d{2}-\d{2}$/.test(update.date) || !Array.isArray(update.items) || !/^docs\/[A-Za-z0-9._-]+\.md$/.test(update.report)) throw new Error('Invalid update entry.');
});
const release = { ...config, version, repository: url.href };
fs.writeFileSync(path.join(root, 'js/local-release.js'), '/* Generated by scripts/build-release.cjs; edit release.json. */\n(function(root){\n    "use strict";\n    root.FocusRelease = Object.freeze(' + JSON.stringify(release, null, 4) + ');\n})(window);\n');
const pkgPath = path.join(root, 'package.json'), pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
pkg.version = version; pkg.author = config.author;
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
let html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
html = html.replace(/<title>[^<]*<\/title>/, '<title>专注清单 · ' + version + ' · ' + config.author + '</title>');
html = html.replace(/\?v=[^"\s]+/g, '?v=' + version);
fs.writeFileSync(path.join(root, 'index.html'), html);
console.log('Generated ' + version + ' from ' + config.repositoryRemote + ': ' + url.href);
